# 球队表
CREATE  TABLE `live_team`(
  `id`  TINYINT(1)  UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `image` VARCHAR(20) NOT NULL  DEFAULT '',
  `type`  TINYINT(1) UNSIGNED NOT NULL  DEFAULT 0,
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

# 直播表
CREATE  TABLE `live_game`(
  `id`  INT(10)  UNSIGNED NOT NULL AUTO_INCREMENT,
  `a_id` TINYINT(1) NOT NULL DEFAULT 0,
  `b_id` TINYINT(1) NOT NULL  DEFAULT 0,
  `a_score` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `b_score` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `narrator` VARCHAR(20)  NOT NULL DEFAULT '',
  `status`  TINYINT(1) UNSIGNED NOT NULL  DEFAULT 0,
  `start_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

# 球员表
CREATE  TABLE `live_player`(
  `id`  INT(10)  UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `image` VARCHAR(20) NOT NULL  DEFAULT '',
  `age` TINYINT(1) UNSIGNED NOT NULL  DEFAULT 0,
  `position` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `update_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

# 赛况表
CREATE  TABLE `live_outs`(
  `id`  INT(10)  UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_id` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `team_id` TINYINT(1) UNSIGNED NOT NULL  DEFAULT 0,
  `content` VARCHAR(200)  NOT NULL  DEFAULT '',
  `image` VARCHAR(20)  NOT NULL DEFAULT '',
  `type` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

# 聊天室
CREATE  TABLE `live_chart`(
  `id`  INT(10)  UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `user_id` TINYINT(1) UNSIGNED NOT NULL  DEFAULT 0,
  `content` VARCHAR(200)  NOT NULL  DEFAULT '',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

# 数据表

CREATE  TABLE `live_data`(
  `id`  INT(10)  UNSIGNED NOT NULL AUTO_INCREMENT,
  `a_id` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `b_id` TINYINT(1) UNSIGNED NOT NULL  DEFAULT 0,
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


